name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04, cc: gcc-12, cxx: g++-12, doc: OFF}
          - {os: ubuntu-22.04, cc: clang-15, cxx: clang++-15, doc: ON}
          - {os: macos-12, cc: gcc-12, cxx: g++-12, doc: OFF}
          - {os: macos-12, cc: /usr/local/opt/llvm/bin/clang, cxx: /usr/local/opt/llvm/bin/clang++, doc: OFF}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install ubuntu dependencies
      if: matrix.os == 'ubuntu-22.04'
      run: >
        sudo apt-get update &&
        sudo apt-get install
        clang-15
        g++-12
        hdf5-tools
        libblas-dev
        libclang-15-dev
        libc++-15-dev
        libc++abi-15-dev
        libomp-15-dev
        libhdf5-dev
        liblapack-dev
        libopenmpi-dev
        openmpi-bin
        openmpi-common
        openmpi-doc
        python3-clang-15
        python3-dev
        python3-mako
        python3-sphinx
        python3-nbsphinx

    - name: Install homebrew dependencies
      if: matrix.os == 'macos-12'
      run: |
        brew install gcc@12 llvm hdf5 open-mpi openblas
        pip3 install mako

    - name: Build cppdlr
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        LIBRARY_PATH: /usr/local/opt/llvm/lib
      run: |
        mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/install -DBuild_Documentation=${{ matrix.doc }}
        make -j2 || make -j1 VERBOSE=1

    - name: Test cppdlr
      env:
        DYLD_FALLBACK_LIBRARY_PATH: /usr/local/opt/llvm/lib
      run: |
        cd build
        ctest -j2 --output-on-failure

    - name: Deploy documentation to website
      if: matrix.doc == ON
      uses: JamesIves/github-pages-deploy-action@v4
      on:
        push:
          branches:
            - main
      with:
        folder: build/doc/html
        branch: github.io
        target-folder: docs