name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    strategy:
      fail-fast: false
      matrix:
        include:
          - {os: ubuntu-22.04, cc: gcc-11, cxx: g++-11}
          - {os: ubuntu-22.04, cc: clang-14, cxx: clang++-14}
          #- {os: macos-12, cc: gcc-11, cxx: g++-11}
          #- {os: macos-12, cc: /usr/local/opt/llvm/bin/clang, cxx: /usr/local/opt/llvm/bin/clang++}

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2

    - name: Install ubuntu dependencies
      if: matrix.os == 'ubuntu-22.04'
      run: >
        sudo apt-get update &&
        sudo apt-get install
        clang-14
        g++-11
        hdf5-tools
        libblas-dev
        libclang-14-dev
        libc++-14-dev
        libc++abi-14-dev
        libomp-14-dev
        libhdf5-dev
        liblapack-dev
        libopenmpi-dev
        openmpi-bin
        openmpi-common
        openmpi-doc
        python3-clang-14
        python3-dev
        python3-mako
        python3-sphinx
        python3-nbsphinx

    - name: Install homebrew dependencies
      if: matrix.os == 'macos-12'
      run: |
        brew install gcc@11 llvm hdf5 open-mpi openblas
        pip3 install mako

    - name: Build cppdlr
      env:
        CC: ${{ matrix.cc }}
        CXX: ${{ matrix.cxx }}
        LIBRARY_PATH: /usr/local/opt/llvm/lib
      run: |
        mkdir build && cd build && cmake .. -DCMAKE_INSTALL_PREFIX=$HOME/install
        make -j2 || make -j1 VERBOSE=1

    - name: Test cppdlr
      env:
        DYLD_FALLBACK_LIBRARY_PATH: /usr/local/opt/llvm/lib
      run: |
        cd build
        ctest -j2 --output-on-failure
